create_pr:
  stage: create_pr
  variables:
    GITHUB_REPO: "Aaron2404/semster-3"
    GITHUB_API_URL: "https://api.github.com/repos/$GITHUB_REPO"
  script:
    - echo "Creating GitHub pull request for $GITHUB_REPO..."
    - |
      PR_RESPONSE=$(curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
           -H "Content-Type: application/json" \
           -d '{
             "title": "'"$CI_MERGE_REQUEST_TITLE"'",
             "body": "This PR mirrors GitLab MR #'"$CI_MERGE_REQUEST_IID"' from '"$CI_PROJECT_URL"'/-/merge_requests/'"$CI_MERGE_REQUEST_IID"'",
             "head": "'"$CI_COMMIT_REF_NAME"'",
             "base": "'"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"'"
           }' \
           $GITHUB_API_URL/pulls)
    - export GITHUB_PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
    - echo "GitHub PR Number: $GITHUB_PR_NUMBER"
    - |
      if [[ -z "$GITHUB_PR_NUMBER" || "$GITHUB_PR_NUMBER" == "null" ]]; then
        echo "Failed to create GitHub pull request."
        echo "Response: $PR_RESPONSE"
        exit 1
      fi
    - echo "GitHub pull request #$GITHUB_PR_NUMBER created successfully."
    - echo "GITHUB_PR_NUMBER=$GITHUB_PR_NUMBER" >> $CI_PROJECT_DIR/.env
  only:
    - merge_requests