run_cypress_tests:
  stage: test
  image: cypress/included:12.0.0
  script:
    - npm ci
    - npm run build
    - npx cypress run --config video=false
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
  only:
    - merge_requests
    - branches