deploy-frontend:
  stage: deploy
  tags:
    - deploy
    - digitalocean
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_DIGITALOCEAN" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
  script:
    - scp -r frontend/dist/* $SERVER_USER@$DROPLET_IP:/var/www/vue-app/
    - ssh $SERVER_USER@$DROPLET_IP 'sudo systemctl restart nginx'
  only:
    - main