stages:
  - build
  - deploy

# Frontend Build
build-frontend:
  stage: build
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week  # Artefacten blijven een week beschikbaar

# Backend Build
build-backend:
  stage: build
  image: gradle:7.6-jdk17  # Gebruik de juiste Gradle/JDK-versie
  script:
    - cd backend
    - ./gradlew build
  artifacts:
    paths:
      - backend/build/libs/
    expire_in: 1 week

# Deployment
deploy-frontend:
  stage: deploy
  image: alpine:latest
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_DIGITALOCEAN" > ~/.ssh/id_digitalocean
    - chmod 600 ~/.ssh/id_digitalocean
    - ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
    - apk add --no-cache openssh
  script:
    - scp -r frontend/dist/* root@$DROPLET_IP:/var/www/html/
  only:
    - deploy/production

deploy-backend:
  stage: deploy
  image: alpine:latest
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_DIGITALOCEAN" > ~/.ssh/id_digitalocean
    - chmod 600 ~/.ssh/id_digitalocean
    - ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
    - apk add --no-cache openssh
  script:
    - scp backend/build/libs/*.jar root@$DROPLET_IP:/path/to/deploy/
    - ssh root@$DROPLET_IP 'systemctl restart elections'
  only:
    - deploy/production
