run_cypress_tests:
  stage: test
  image: cypress/included:12.0.0
  script:
    - npm ci
    - npm run build
    - npx cypress run --env TS=true
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
  only:
    - main
