gradle-test-coverage:
  stage: test
  image: openjdk:21-jdk-slim
  script:
    - cd backend
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - backend/build/test-results
      - backend/build/reports/jacoco/test
  only:
    - main

cypress-test:
  stage: test
  image: cypress/included:12.5.0
  script:
    - cd frontend
    - npm install
    - npm run test
  dependencies:
    - gradle-test-coverage
  only:
    - main

sonarqube-analysis:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - cd frontend
    - sonar-scanner
  dependencies:
    - gradle-test-coverage
    - cypress-test
  variables:
    SONAR_TOKEN: $SONAR_TOKEN
  only:
    - main

