stages:
  - build
  - deploy

# Frontend Build
build-frontend:
  stage: build
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week  # Artefacten blijven een week beschikbaar

# Backend Build
build-backend:
  stage: build
  image: gradle:8.10.1-jdk21
  script:
    - cd backend
    - ./gradlew build
  artifacts:
    paths:
      - backend/build/libs/
    expire_in: 1 week

# Deployment
deploy-frontend:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh  # Installeer OpenSSH
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_DIGITALOCEAN" > ~/.ssh/id_digitalocean
    - chmod 600 ~/.ssh/id_digitalocean
    - ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts  # Voeg host key toe
  script:
    - scp -r frontend/dist/* root@$DROPLET_IP:/var/www/vue-app/  # Kopieer bestanden
    - ssh root@$DROPLET_IP 'sudo systemctl restart nginx'  # Restart Nginx
  only:
    - deploy/production

deploy-backend:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh  # Installeer OpenSSH
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_DIGITALOCEAN" > ~/.ssh/id_digitalocean
    - chmod 600 ~/.ssh/id_digitalocean
    - ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts  # Voeg host key toe
  script:
    - scp backend/build/libs/*.jar root@$DROPLET_IP:/opt/elections/  # Kopieer bestanden
    - ssh root@$DROPLET_IP 'sudo systemctl restart elections'  # Restart backend-service
  only:
    - deploy/production
