run_cypress_tests:
  stage: test
  image: cypress/browsers:22.12.0
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - curl -sSL https://get.docker.com/ | sh
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - apt-get update && apt-get install -y nodejs npm
    - docker-compose up -d
    - cd frontend
    - npm i
  script:
    - npx cypress run
  after_script:
    - docker-compose down
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
  only:
    - merge_requests
    - branches
