run_cypress_tests:
  stage: test
  image: cypress/included:12.0.0
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - cd frontend
  script:
    - npm i
    - npm run build
    - npx cypress run
  after_script:
    - docker-compose down
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
  only:
    - merge_requests
    - branches