sonarqube-analysis:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner
  variables:
    SONAR_TOKEN: $SONAR_TOKEN
  only:
    - main
