run_cypress_tests:
  stage: test
  image: docker:latest
  services:
    - name: docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker-compose up -d
    - cd frontend
  script:
    - npm ci
    - npx cypress run
  after_script:
    - docker-compose down
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
  only:
    - merge_requests
    - branches
