version: '3.9'

services:
  backend:
    volumes:
      - ./backend/config:/app/config
      - ./backend/build/libs/app.jar:/app/app.jar
    environment:
      SPRING_CONFIG_LOCATION: /app/config/application.properties
    command: ["java", "-jar", "/app/app.jar"]

  frontend:
    volumes:
      - ./frontend:/usr/share/nginx/html
    environment:
      VUE_APP_BACKEND_URL: http://localhost:8080

  mysql:
    ports:
      - "3307:3306" # Change port for local dev
