services:
  web:
    image: elections-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "7419:7419"
    depends_on:
      - api
    networks:
      - election-network
    restart: unless-stopped

  api:
    image: elections-backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "7420:7420"
    depends_on:
      - database
    networks:
      - election-network
    environment:
      PG_HOST: database
    restart: unless-stopped

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: elections
    volumes:
      - hva-elections:/var/lib/postgresql/data
    networks:
      - election-network
    restart: unless-stopped

volumes:
  hva-elections:

networks:
  election-network:
    driver: bridge
