site_name: Visie op de uitslag
site_description: Documentatie voor ons project

theme:
  name: material

docs_dir: documentation
site_dir: public

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.extra

extra_javascript:
  - "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"